/* Generated by build.js. */
window.SLV_UPCOMING = [{"id":"access","name":"Access control","blurb":"Card readers, door hardware, and controllers"},{"id":"cctv","name":"CCTV","blurb":"Cameras, recorders, and network video"}];
