/* Generated by build.js. */
window.SLV_UPCOMING = [{"id":"access","name":"Access control","blurb":"Card readers, locks, door hardware, and egress rules"},{"id":"cctv","name":"CCTV","blurb":"Cameras, recorders, and network video"}];
